# Generated by Django 5.0.4 on 2024-04-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_person_alter_historicalperformance_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterModelTable(
            name='historicalperformance',
            table='HistoricalPerformance_Table',
        ),
    ]
