# Generated by Django 5.0.4 on 2024-06-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_student_remove_purchaseorder_vendor_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student_Table',
        ),
    ]
